ALTER TABLE users ENABLE ROW LEVEL SECURITY;

ALTER TABLE sites ENABLE ROW LEVEL SECURITY;

ALTER TABLE installations ENABLE ROW LEVEL SECURITY;

ALTER TABLE idempotency_keys ENABLE ROW LEVEL SECURITY;
